#!/bin/sh

export PLTCOMPILEDROOTS='compiled/debug:'
# -j to disable jit, -w debug to see all debug info
#racket -j -W debug -t rawind.rkt -- --debug
#racket --no-jit -l errortrace -l rawind -- --debug
racket --no-jit -l errortrace -l rawind -- --debug
